### PR TITLE
Player count update

### LINKED ISSUE #30: Player count doesn't update for hubs/areas in ARUP
The player count only updates when you move around and not when someone joins/leaves

### PR DESCRIPTION
**Pull request by EstatoDeviato**
closes #30

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Can you split this up so it only focuses on fixing the bug? Currently the PR has added features that I want to address in a different pr specific to them (such as mod count etc)

**Comment by EstatoDeviato** [comment]
Sure!

**Comment by Crystalwarrior** [comment]
Hmm, looks good. Let's try it out.

**Comment by Crystalwarrior** [comment]
Waaait wait wait, FA packet is kind of expensive. Wouldn't this create lag spikes any time a client triggers the call?

**Comment by EstatoDeviato** [comment]
I don't think so because it uses FA packet only if you are in hub_viewing

**Comment by EstatoDeviato** [comment]
However I don't know how to upgrade player count when a player joins in to the server. I tried every new_client function but nothing

**Comment by EstatoDeviato** [comment]
Maybe I can optimize something

**Review by Crystalwarrior — CHANGES_REQUESTED** [review]

**Comment by EstatoDeviato** [comment]
to count players I made 2 loops instead of 3, because I need to divide the counters to hubs.
To send player upgrade I made 1 loop instead of 3

**Review by EstatoDeviato — COMMENTED** [review]
to count players I made 2 loops instead of 3, because I need to divide the counters to hubs.
To send players count upgrade I made 1 loop instead of 3

**Review by Crystalwarrior — APPROVED** [review]

**Pull request merged**
