### PR TITLE
Separating classes

### PR DESCRIPTION
**Pull request by caleb-mabry**
Separate out Client and Client Manager to make things easier to read

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
yes plz

**Comment by stonedDiscord** [comment]
then why didn't you merge it?
now it has merge conflicts all over

**Comment by Crystalwarrior** [comment]
> then why didn't you merge it? now it has merge conflicts all over

I forgor,💀

**Comment by caleb-mabry** [comment]
Slow turnaround time. Not bothering with it anymore, lol

**Pull request closed without merging**
